version: "3.8"

services:

  # Joined service & DB
  joined:
    image: partytimecontainerregistry.azurecr.io/joined
    build:
      context: .././Partytime.Joined
      dockerfile: Dockerfile
    container_name: joined
    hostname: joined
    ports:
      - "5004:5004"
    depends_on:
    - rabbitmq
    - joinedpostgresql
    networks:
      - Partytime

  joinedpostgresql:
    image: postgres:15.3-alpine
    container_name: joinedpostgresql
    restart: always
    environment:
      - POSTGRES_USER=tommie
      - POSTGRES_PASSWORD=FHk562I6jRC78U9q
      - POSTGRES_DB=joined
    ports:
      - '5433:5432'
    volumes:
      - joinedpostgresql:/var/lib/postgresql/data
      - ./docker_postgres_joined.sql:/docker-entrypoint-initdb.d/docker_postgres_joined.sql 
    networks:
      - Partytime
    
  # Party service & DB
  party:
    image: partytimecontainerregistry.azurecr.io/party
    build:
      context: .././Partytime.Party
      dockerfile: Dockerfile
    container_name: party
    hostname: party
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
      - partypostgresql
    networks:
      - Partytime

  partypostgresql:
    image: postgres:15.3-alpine
    container_name: partypostgresql
    restart: always
    environment:
      - POSTGRES_USER=tommie
      - POSTGRES_PASSWORD=Rfec7Fo81YchjyUu
      - POSTGRES_DB=party
    ports:
      - '5432:5432'
    volumes: 
      - partypostgresql:/var/lib/postgresql/data
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    networks:
      - Partytime

  # Authentication
  authenticationwebapi:
    #image: partytimecontainerregistry.azurecr.io/authentication
    build:
      context: .././Partytime.Authentication
      dockerfile: Dockerfile
    container_name: authentication
    hostname: authenticationwebapi
    # depends_on:
    #   - userpostgresql
    ports: 
    - 80
    networks:
      - Partytime

  userpostgresql:
    image: postgres:15.3-alpine
    container_name: userpostgresql
    restart: always
    environment:
      - POSTGRES_USER=tomoli
      - POSTGRES_PASSWORD=34Bn473OaN76qBT7
      - POSTGRES_DB=users
    ports:
      - '5435:5432'
    volumes: 
      - userpostgresql:/var/lib/postgresql/data
      - ./docker_postgres_init_users.sql:/docker-entrypoint-initdb.d/docker_postgres_init_users.sql
    networks:
      - Partytime

  # Gateway
  apigateway:
    #image: partytimecontainerregistry.azurecr.io/authentication
    build:
      context: .././ApiGateway
      dockerfile: Dockerfile
    container_name: apigateway
    hostname: apigateway
    ports: 
      - "8001:80"
    networks:
      - Partytime

  # Messaging
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq
    networks:
      - Partytime

networks:
  Partytime:

volumes:
  party:
  partypostgresql:
  joined:
  joinedpostgresql:
  authenticationwebapi:
  #userpostgresql:
  rabbitmqdata:
  rabbitmq: