version: "3.8"

services:

  # Joined service & DB
  joined:
    image: partytimecontainerregistry.azurecr.io/joined
    build:
      context: .././Partytime.Joined
      dockerfile: Dockerfile
    container_name: partytime-joined-service
    hostname: partytime-joined-service
    ports:
      - "5004:5004"
    depends_on:
    - rabbitmq
    - joinedpostgresql
    networks:
      - Partytime

  joinedpostgresql:
    image: postgres:15.3-alpine
    container_name: joinedpostgresql
    restart: always
    environment:
      - POSTGRES_USER=tommie
      - POSTGRES_PASSWORD=FHk562I6jRC78U9q
      - POSTGRES_DB=joined
    ports:
      - '5433:5432'
    volumes:
      - joinedpostgresql:/var/lib/postgresql/data
      - ./docker_postgres_joined.sql:/docker-entrypoint-initdb.d/docker_postgres_joined.sql 
    networks:
      - Partytime
  
  pgadmin-join-compose:
    image: dpage/pgadmin4
    environment:
        PGADMIN_DEFAULT_EMAIL: "test@gmail.com"
        PGADMIN_DEFAULT_PASSWORD: "test123!"
    ports:
        - "16545:80"
    depends_on:
        - joinedpostgresql
    networks:
      - Partytime  
    
  # Party service & DB
  party:
    image: partytimecontainerregistry.azurecr.io/party
    build:
      context: .././Partytime.Party
      dockerfile: Dockerfile
    container_name: partytime-party-service
    hostname: partytime-party-service
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
      - partypostgresql
    networks:
      - Partytime

  partypostgresql:
    image: postgres:15.3-alpine
    container_name: partypostgresql
    restart: always
    environment:
      - POSTGRES_USER=tommie
      - POSTGRES_PASSWORD=Rfec7Fo81YchjyUu
      - POSTGRES_DB=party
    ports:
      - '5432:5432'
    volumes: 
      - partypostgresql:/var/lib/postgresql/data
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    networks:
      - Partytime

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
        PGADMIN_DEFAULT_EMAIL: "test@gmail.com"
        PGADMIN_DEFAULT_PASSWORD: "test123!"
    ports:
        - "16543:80"
    depends_on:
        - partypostgresql
    networks:
      - Partytime

  # Authentication
  authenticationwebapi:
    image: partytimecontainerregistry.azurecr.io/authentication
    build:
      context: .././Partytime.Authentication
      dockerfile: Dockerfile
    container_name: authentication-webapi
    ports: 
    - 80
    networks:
      - Partytime

  # Gateway
  apigateway:
    image: partytimecontainerregistry.azurecr.io/apigateway
    build:
      context: .././ApiGateway
      dockerfile: Dockerfile
    container_name: api-gateway
    hostname: api-gateway
    ports: 
      - "8001:80"
    networks:
      - Partytime

  # Messaging
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq
    networks:
      - Partytime

networks:
  Partytime:

volumes:
  party:
  partypostgresql:
  joined:
  joinedpostgresql:
  authenticationwebapi:
  rabbitmqdata:
  rabbitmq: